---
- name: Deploy Website
  hosts: app
  become: yes

  tasks:

    - name: Pull latest image
      shell: docker pull kaushal2608/capstone-website:latest

    - name: Stop old container
      shell: docker stop capstone
      ignore_errors: yes

    - name: Remove old container
      shell: docker rm capstone
      ignore_errors: yes

    - name: Run new container
      shell: docker run -d --name capstone -p 80:80 --restart always kaushal2608/capstone-website:latest
